### ISSUE TITLE
Separate Attack/Release times

### ISSUE THREAD

**Issue by unfa** [jpcima/spectral#4]
The current Release time seems to actually act like both Attack and Release at the same time.

Maybe it'd be good to split them up and provide a "lock" option to have them paired?

Also - infinite release time would work effectively as a "hold max" mode, am I right?

**Comment by jpcima** [comment]
At present it works at the time constant of a lowpass filter.
So the name "release" is a bit a lie at this moment, since there aren't separate A and R.

It's a rather trivial feature to make, so I don't have a problem about adding it.
(in fact I wanted and kinda forgot, so thanks for reminding :grin:)

>Also - infinite release time would work effectively as a "hold max" mode, am I right?

No that would make it a "hold" mode, that discards input and maintains what was last in there as the feedback value.

**Comment by jpcima** [comment]
implemented in 0580881.
This makes the attack significantly more responsive with the default setting.
Let me know if you'd like more range.

**Comment by unfa** [comment]
Thanks! Will test!
